### ISSUE TITLE
10.4 Manipulating the DOM Typos

### ISSUE THREAD

**Issue by ZebGirouard** [GA-WDI/fundamentals#327] opened 2016-10-07 20:09 UTC
- What's going on here http://fundamentals.generalassemb.ly/10_chapter/10_lesson.html#events

Weird bullet:  '` - The dot ties the method on the right hand side (addEventListener`) with the element on the left hand side.'

**Comment by microsarah** [comment] 2016-10-10 18:37
duplicate of #301

**Closed by microsarah** 2016-10-10 18:37 UTC
Labels: Current Sprint
